
apiVersion: v2
name: app-translator
description: Application for translating text
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: Esti Genauer
    email: genauer1997@gmail.com
